# Generated by Django 5.0.6 on 2024-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
